=== ibm-iib-demo-vs-org/fund-transfer/FundTransferLib/BLACK.OUT.DATES.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified"
	targetNamespace="urn:esbbank.com/gbo/xml/schemas/v1_0/" version="1.0"
	xmlns:esbbankgbo="urn:esbbank.com/gbo/xml/schemas/v1_0/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
       <xsd:include schemaLocation="CommonTypes.xsd"></xsd:include>	

	<xsd:element name="GetBlackOutDatesRequest" type="esbbankgbo:GetBlackOutDatesRequest"></xsd:element>
	
	<xsd:complexType name="GetBlackOutDatesRequest"> 
		<xsd:sequence>
			<xsd:element name="eAI_HEADER" type="esbbankgbo:EAI_HEADER" />
			<xsd:element name="eAI_BODY" type="esbbankgbo:GetBlackOutDatesRequestBody" />
		</xsd:sequence>
	</xsd:complexType>
	


	<xsd:complexType name="GetBlackOutDatesRequestBody">
		<xsd:sequence>
					
					<xsd:element maxOccurs="1" minOccurs="1" name="year" type="xsd:string" />
					<xsd:element maxOccurs="1" minOccurs="0" name="currency" type="xsd:string" />
		
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="GetBlackOutDatesReply" type="esbbankgbo:GetBlackOutDatesReply"></xsd:element>
	
	<xsd:complexType name="GetBlackOutDatesReply">
		<xsd:sequence>
			<xsd:element name="eAI_HEADER" type="esbbankgbo:EAI_HEADER" />
			<xsd:element name="eAI_BODY" type="esbbankgbo:GetBlackOutDatesReplyBody" minOccurs="0"/>
			<xsd:element name="eAI_STATUS" type="esbbankgbo:EAI_STATUS"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="GetBlackOutDatesReplyBody">
		<xsd:sequence>
		<xsd:element maxOccurs="unbounded" minOccurs="0" name="blackOutDate"	type="esbbankgbo:BlackOutDate" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="BlackOutDate">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="day"
				type="esbbankgbo:Date" />

		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== ibm-iib-demo-vs-org/fund-transfer/FundTransferLib/BLACK.OUT.DATES.rep.xml
<?xml version="1.0" encoding="UTF-8"?>
<esbbankgbo:GetBlackOutDatesReply xmlns:esbbankgbo="urn:esbbank.com/gbo/xml/schemas/v1_0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:esbbank.com/gbo/xml/schemas/v1_0/ BLACK.OUT.DATES.xsd ">
  <esbbankgbo:eAI_HEADER>esbbankgbo:eAI_HEADER</esbbankgbo:eAI_HEADER>
  <esbbankgbo:eAI_BODY>
    <esbbankgbo:blackOutDate>
      <esbbankgbo:day>esbbankgbo:day</esbbankgbo:day>
    </esbbankgbo:blackOutDate>
    <esbbankgbo:blackOutDate>
      <esbbankgbo:day>esbbankgbo:day</esbbankgbo:day>
    </esbbankgbo:blackOutDate>
  </esbbankgbo:eAI_BODY>
  <esbbankgbo:eAI_STATUS>esbbankgbo:eAI_STATUS</esbbankgbo:eAI_STATUS>
</esbbankgbo:GetBlackOutDatesReply>
